export interface CategoryDef {
  slug: string
  name: string
  icon: string
  description: string
  children: { slug: string; name: string; description?: string }[]
}

export const CATEGORIES: CategoryDef[] = [
  {
    slug: 'jichu',
    name: '基础理论',
    icon: 'book-open',
    description: '中医基本理论体系，阴阳五行、藏象、气血津液等核心学说',
    children: [
      { slug: 'jichu-yinyang', name: '阴阳学说' },
      { slug: 'jichu-wuxing', name: '五行学说' },
      { slug: 'jichu-cangxiang', name: '藏象学说' },
      { slug: 'jichu-qixue', name: '气血津液神' },
      { slug: 'jichu-bingyin', name: '病因学说' },
      { slug: 'jichu-bingji', name: '病机学说' },
      { slug: 'jichu-zhize', name: '治则治法' },
      { slug: 'jichu-zhexue', name: '中医哲学与思维' },
    ],
  },
  {
    slug: 'zhenduan',
    name: '诊断方法',
    icon: 'stethoscope',
    description: '望闻问切四诊及各种辨证方法',
    children: [
      { slug: 'zhenduan-wangzhen', name: '望诊' },
      { slug: 'zhenduan-wenzhen', name: '闻诊' },
      { slug: 'zhenduan-wenzhen2', name: '问诊' },
      { slug: 'zhenduan-maizhen', name: '脉诊/切诊' },
      { slug: 'zhenduan-fuzhen', name: '腹诊' },
      { slug: 'zhenduan-shezhen', name: '舌诊' },
      { slug: 'zhenduan-bagang', name: '八纲辨证' },
      { slug: 'zhenduan-zangfu', name: '脏腑辨证' },
      { slug: 'zhenduan-liujing', name: '六经辨证' },
      { slug: 'zhenduan-weiqiyingxue', name: '卫气营血辨证' },
      { slug: 'zhenduan-sanjiao', name: '三焦辨证' },
      { slug: 'zhenduan-jingluo', name: '经络辨证' },
    ],
  },
  {
    slug: 'zhongyao',
    name: '中药学',
    icon: 'leaf',
    description: '中药的性味归经、功效主治、用法用量',
    children: [
      { slug: 'zhongyao-jichu', name: '中药基础理论' },
      { slug: 'zhongyao-jiebiao', name: '解表药' },
      { slug: 'zhongyao-qingre', name: '清热药' },
      { slug: 'zhongyao-xiexia', name: '泻下药' },
      { slug: 'zhongyao-qufengshi', name: '祛风湿药' },
      { slug: 'zhongyao-huashi', name: '化湿药' },
      { slug: 'zhongyao-lishuishenshi', name: '利水渗湿药' },
      { slug: 'zhongyao-wenli', name: '温里药' },
      { slug: 'zhongyao-liqi', name: '理气药' },
      { slug: 'zhongyao-xiaoshi', name: '消食药' },
      { slug: 'zhongyao-quchong', name: '驱虫药' },
      { slug: 'zhongyao-zhixue', name: '止血药' },
      { slug: 'zhongyao-huoxuehuayu', name: '活血化瘀药' },
      { slug: 'zhongyao-huatanzhikepingchuan', name: '化痰止咳平喘药' },
      { slug: 'zhongyao-anshen', name: '安神药' },
      { slug: 'zhongyao-pingganxifeng', name: '平肝息风药' },
      { slug: 'zhongyao-kaiqiao', name: '开窍药' },
      { slug: 'zhongyao-buxu', name: '补虚药' },
      { slug: 'zhongyao-souse', name: '收涩药' },
      { slug: 'zhongyao-yongtu', name: '涌吐药' },
      { slug: 'zhongyao-waiyong', name: '外用药' },
      { slug: 'zhongyao-paozhi', name: '中药炮制' },
      { slug: 'zhongyao-peiwu', name: '中药配伍与禁忌' },
    ],
  },
  {
    slug: 'fangji',
    name: '方剂学',
    icon: 'beaker',
    description: '经典方剂组成、功效、主治、加减变化',
    children: [
      { slug: 'fangji-jichu', name: '方剂基础理论' },
      { slug: 'fangji-jiebiao', name: '解表剂' },
      { slug: 'fangji-xiexia', name: '泻下剂' },
      { slug: 'fangji-hejie', name: '和解剂' },
      { slug: 'fangji-qingre', name: '清热剂' },
      { slug: 'fangji-wenli', name: '温里剂' },
      { slug: 'fangji-buyi', name: '补益剂' },
      { slug: 'fangji-guse', name: '固涩剂' },
      { slug: 'fangji-anshen', name: '安神剂' },
      { slug: 'fangji-kaiqiao', name: '开窍剂' },
      { slug: 'fangji-liqi', name: '理气剂' },
      { slug: 'fangji-lixue', name: '理血剂' },
      { slug: 'fangji-zhifeng', name: '治风剂' },
      { slug: 'fangji-zhizao', name: '治燥剂' },
      { slug: 'fangji-qushi', name: '祛湿剂' },
      { slug: 'fangji-qutan', name: '祛痰剂' },
      { slug: 'fangji-xiaoshi', name: '消食剂' },
      { slug: 'fangji-quchong', name: '驱虫剂' },
      { slug: 'fangji-jingdian', name: '经典名方' },
    ],
  },
  {
    slug: 'jingluo',
    name: '经络腧穴',
    icon: 'map-pin',
    description: '十二正经、奇经八脉、腧穴定位与主治',
    children: [
      { slug: 'jingluo-zonglun', name: '经络总论' },
      { slug: 'jingluo-shier', name: '十二正经' },
      { slug: 'jingluo-qijing', name: '奇经八脉' },
      { slug: 'jingluo-luomai', name: '十五络脉' },
      { slug: 'jingluo-jingbie', name: '十二经别' },
      { slug: 'jingluo-jingjin', name: '十二经筋' },
      { slug: 'jingluo-pibu', name: '十二皮部' },
      { slug: 'jingluo-shuxue', name: '腧穴总论' },
      { slug: 'jingluo-tedingxue', name: '特定穴' },
      { slug: 'jingluo-jingwai', name: '经外奇穴' },
    ],
  },
  {
    slug: 'zhenjiu',
    name: '针灸学',
    icon: 'target',
    description: '针法、灸法及各种针灸疗法',
    children: [
      { slug: 'zhenjiu-zhenfa', name: '针法' },
      { slug: 'zhenjiu-jiufa', name: '灸法' },
      { slug: 'zhenjiu-dianzhen', name: '电针' },
      { slug: 'zhenjiu-erzhen', name: '耳针/耳穴' },
      { slug: 'zhenjiu-touzhen', name: '头针' },
      { slug: 'zhenjiu-wanhuaizhen', name: '腕踝针' },
      { slug: 'zhenjiu-peixue', name: '针灸处方与配穴' },
      { slug: 'zhenjiu-linchuang', name: '针灸临床治疗' },
    ],
  },
  {
    slug: 'tuina',
    name: '推拿按摩',
    icon: 'hand',
    description: '推拿手法、成人推拿、小儿推拿',
    children: [
      { slug: 'tuina-shoufa', name: '推拿手法' },
      { slug: 'tuina-chengren', name: '成人推拿治疗' },
      { slug: 'tuina-xiaoer', name: '小儿推拿' },
      { slug: 'tuina-zhenggu', name: '正骨手法' },
      { slug: 'tuina-baojian', name: '自我保健按摩' },
    ],
  },
  {
    slug: 'baguan',
    name: '拔罐疗法',
    icon: 'circle',
    description: '拔罐方法、适应症及治疗方案',
    children: [
      { slug: 'baguan-jichu', name: '拔罐基础' },
      { slug: 'baguan-fangfa', name: '拔罐方法' },
      { slug: 'baguan-zhiliao', name: '常见病拔罐方案' },
    ],
  },
  {
    slug: 'guasha',
    name: '刮痧疗法',
    icon: 'wind',
    description: '刮痧工具、手法、部位及治疗方案',
    children: [
      { slug: 'guasha-jichu', name: '刮痧基础' },
      { slug: 'guasha-buwei', name: '刮痧部位与经络' },
      { slug: 'guasha-zhiliao', name: '常见病刮痧方案' },
    ],
  },
  {
    slug: 'shiliao',
    name: '食疗药膳',
    icon: 'utensils',
    description: '食物性味归经、药膳配方、体质食疗',
    children: [
      { slug: 'shiliao-shicai', name: '食材药性' },
      { slug: 'shiliao-yaoshan', name: '药膳配方' },
      { slug: 'shiliao-tizhi', name: '体质食疗方案' },
      { slug: 'shiliao-jijie', name: '季节/节气养生饮食' },
      { slug: 'shiliao-jinji', name: '食疗禁忌' },
      { slug: 'shiliao-yaojiu', name: '药酒/药茶' },
    ],
  },
  {
    slug: 'gongfa',
    name: '养生功法',
    icon: 'activity',
    description: '八段锦、五禽戏、太极拳、站桩等传统功法',
    children: [
      { slug: 'gongfa-baduanjin', name: '八段锦' },
      { slug: 'gongfa-wuqinxi', name: '五禽戏' },
      { slug: 'gongfa-taiji', name: '太极拳' },
      { slug: 'gongfa-yijinjing', name: '易筋经' },
      { slug: 'gongfa-liuzijue', name: '六字诀' },
      { slug: 'gongfa-zhanzhuang', name: '站桩' },
      { slug: 'gongfa-daoyin', name: '导引术' },
      { slug: 'gongfa-qigong', name: '气功基础' },
      { slug: 'gongfa-tuna', name: '呼吸吐纳' },
      { slug: 'gongfa-jingzuo', name: '冥想/静坐' },
    ],
  },
  {
    slug: 'dianji',
    name: '中医典籍',
    icon: 'scroll',
    description: '经典医书原文、注解与学习笔记',
    children: [
      { slug: 'dianji-huangdi', name: '《黄帝内经》' },
      { slug: 'dianji-nanjing', name: '《难经》' },
      { slug: 'dianji-shanghan', name: '《伤寒论》' },
      { slug: 'dianji-jinkui', name: '《金匮要略》' },
      { slug: 'dianji-shennong', name: '《神农本草经》' },
      { slug: 'dianji-bencao', name: '《本草纲目》' },
      { slug: 'dianji-wenbing', name: '《温病条辨》' },
      { slug: 'dianji-binhu', name: '《濒湖脉学》' },
      { slug: 'dianji-zhenjiu', name: '《针灸甲乙经》' },
      { slug: 'dianji-qianjin', name: '《千金要方》' },
      { slug: 'dianji-yizong', name: '《医宗金鉴》' },
      { slug: 'dianji-qita', name: '其他典籍' },
    ],
  },
  {
    slug: 'linchuang',
    name: '临床各科',
    icon: 'clipboard',
    description: '中医内科、外科、妇科、儿科等临床诊疗',
    children: [
      { slug: 'linchuang-neike', name: '中医内科' },
      { slug: 'linchuang-waike', name: '中医外科' },
      { slug: 'linchuang-fuke', name: '中医妇科' },
      { slug: 'linchuang-erke', name: '中医儿科' },
      { slug: 'linchuang-wuguanke', name: '中医五官科' },
      { slug: 'linchuang-gushang', name: '中医骨伤科' },
      { slug: 'linchuang-zhongliu', name: '中医肿瘤' },
      { slug: 'linchuang-jizheng', name: '中医急症' },
    ],
  },
  {
    slug: 'tizhi',
    name: '体质辨识',
    icon: 'user',
    description: '九种体质辨识及调理方案',
    children: [
      { slug: 'tizhi-pinghe', name: '平和质' },
      { slug: 'tizhi-qixu', name: '气虚质' },
      { slug: 'tizhi-yangxu', name: '阳虚质' },
      { slug: 'tizhi-yinxu', name: '阴虚质' },
      { slug: 'tizhi-tanshi', name: '痰湿质' },
      { slug: 'tizhi-shire', name: '湿热质' },
      { slug: 'tizhi-xueyu', name: '血瘀质' },
      { slug: 'tizhi-qiyu', name: '气郁质' },
      { slug: 'tizhi-tebing', name: '特禀质' },
      { slug: 'tizhi-tiaoli', name: '体质调理方案' },
    ],
  },
  {
    slug: 'mingyi',
    name: '名医传承',
    icon: 'award',
    description: '古今名医生平、学术思想、经典医案',
    children: [
      { slug: 'mingyi-gudai', name: '古代名医' },
      { slug: 'mingyi-jindai', name: '近现代名医' },
      { slug: 'mingyi-xueshuo', name: '各家学说' },
      { slug: 'mingyi-yian', name: '经典医案' },
    ],
  },
  {
    slug: 'waizhi',
    name: '中药外治',
    icon: 'layers',
    description: '膏药、熏洗、敷脐、热熨等外治疗法',
    children: [
      { slug: 'waizhi-gaoyao', name: '膏药/贴敷' },
      { slug: 'waizhi-xunxi', name: '熏洗疗法' },
      { slug: 'waizhi-fuqi', name: '敷脐疗法' },
      { slug: 'waizhi-reyun', name: '中药热熨' },
      { slug: 'waizhi-guanchang', name: '中药灌肠' },
    ],
  },
  {
    slug: 'minjian',
    name: '民间疗法',
    icon: 'home',
    description: '民间验方、土方及各种特色疗法（需注意安全）',
    children: [
      { slug: 'minjian-aiye', name: '艾叶疗法' },
      { slug: 'minjian-fengliao', name: '蜂疗' },
      { slug: 'minjian-shaliao', name: '沙疗' },
      { slug: 'minjian-huoliao', name: '火疗' },
      { slug: 'minjian-yanfang', name: '验方/土方' },
      { slug: 'minjian-pianfang', name: '民间偏方' },
    ],
  },
  {
    slug: 'jiehe',
    name: '中西医结合',
    icon: 'git-merge',
    description: '中西医对照、现代药理研究、结合治疗方案',
    children: [
      { slug: 'jiehe-duizhao', name: '常见病中西医对照' },
      { slug: 'jiehe-yaoli', name: '中药现代药理研究' },
      { slug: 'jiehe-tijian', name: '体检指标中医解读' },
      { slug: 'jiehe-zhiliao', name: '中西医结合治疗' },
    ],
  },
]
